name: Directory Organize on Push
on:
  push:

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of tracked files except .github/workflows
        id: files
        run: |
          files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -v '^.github/workflows' || true)
          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$files" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create directories for each file's top-level folder
        if: ${{ steps.files.outputs.files != '' }}
        run: |
          IFS=$'\n' read -rd '' -a file_array <<< "${{ steps.files.outputs.files }}"
          for file in "${file_array[@]}"; do
            topdir=$(echo "$file" | cut -d '/' -f1)
            if [ -n "$topdir" ] && [ ! -d "sorted/$topdir" ] && [ "$topdir" != "sorted" ]; then
              mkdir -p "sorted/$topdir"
            fi
          done

      - name: Move files except .github/workflows into sorted
        if: ${{ steps.files.outputs.files != '' }}
        run: |
          for f in ${{ steps.files.outputs.files }}; do
            parent_dir=$(dirname "$f")
            if [ "$parent_dir" = "." ]; then
              mv "$f" sorted/
            else
              mkdir -p "sorted/$parent_dir"
              mv "$f" "sorted/$parent_dir"
            fi
          done

      - name: List files in sorted directory
        if: ${{ steps.files.outputs.files != '' }}
        run: ls -l sorted

      - name: List files in root directory (to verify .github is untouched)
        run: ls -l
